### ISSUE TITLE
Can't run the perl scrot

### ISSUE THREAD

**Issue by twyK** [jackthesmack/IdleTime#2]
![72rcdlt](https://cloud.githubusercontent.com/assets/16549707/12671839/901502f6-c672-11e5-9a85-af6abee1e125.png)
@jackthesmack

**Comment by jack-cole** [comment]
On line 28 where it says `no warnings "experimental::autoderef";` add a # in front of it so it says `#no warnings "experimental::autoderef";`

Or download the latest version of **idletime.pl** and replace your current one.

See if that fixes it.

**Comment by twyK** [comment]
Now it works thanks you :D
